name: DashLord scans

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Single url to scan or scan all urls"
        required: false
        default: ""
      tags:
        description: "Comma-separated tags to filter urls to scan"
        required: false
        default: "production"
      tool:
        description: "Single tool to run or use all tools"
        type: choice
        default: all
        options:
          - all
          - codescan
          - dependabot
          - ecoindex
          - lighthouse
          - sonarcloud
          - trivy
          - zap
          - dsfr
          - ecoindex
  push:
    branches:
      - main
    paths:
      - "dashlord.yaml"
      - "dashlord.yml"
      - "urls.txt"
  schedule:
    - cron: "0 0 * * 0" # see https://crontab.guru

# allow only one concurrent scan action
concurrency:
  cancel-in-progress: true
  group: scans

permissions:
  contents: write

jobs:
  init:
    runs-on: ubuntu-latest
    name: Prepare
    outputs:
      sites: ${{ steps.init.outputs.sites }}
      config: ${{ steps.init.outputs.config }}
    steps:
      - name: Set tags output
        id: tags
        run: |
         TAGS_INPUT=${{ github.event.inputs.tags }}
         echo "::set-output name=value::${TAGS_INPUT:-"production"}"
      - uses: actions/checkout@v6
      - id: init
        uses: SocialGouv/dashlord-actions/init@bda592c644a12e09736c4884426abd37280faa2d # 1.44.0
        with:
          url: ${{ github.event.inputs.url }}
          tool: ${{ github.event.inputs.tool }}
          tags: ${{ steps.tags.outputs.value }}
      - id: updown-init
        if: ${{ matrix.sites.tools.updownio }}
        uses: SocialGouv/dashlord-actions/updown-init@bda592c644a12e09736c4884426abd37280faa2d # 1.44.0
        env:
          UPDOWNIO_API_KEY: ${{ secrets.UPDOWNIO_API_KEY }}

  scans:
    runs-on: ubuntu-latest
    name: Scan
    needs: init
    continue-on-error: true
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        sites: ${{ fromJson(needs.init.outputs.sites) }}
    steps:
      - uses: actions/checkout@v6

      - run: |
          mkdir scans

      - uses: actions/cache@v5
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: dsfr
        continue-on-error: true
        timeout-minutes: 10
        uses: SocialGouv/dashlord-actions/dsfr@bda592c644a12e09736c4884426abd37280faa2d # 1.44.0
        if: ${{ matrix.sites.tools.dsfr }}
        with:
          url: ${{ matrix.sites.url }}
          output: scans/dsfr.json

      - name: eco-index
        continue-on-error: true
        timeout-minutes: 10
        uses: SocialGouv/dashlord-actions/ecoindex@bda592c644a12e09736c4884426abd37280faa2d # 1.44.0
        if: ${{ matrix.sites.tools.ecoindex }}
        with:
          url: ${{ matrix.sites.url }}
          output: scans/ecoindex.json

      - name: Screenshot Website
        uses: swinton/screenshot-website@80a97add3949213d227d3366c2309c9ba721f6b5 # v1.0.2
        if: ${{ matrix.sites.tools.screenshot }}
        continue-on-error: true
        timeout-minutes: 10
        with:
          source: "${{ matrix.sites.url }}"
          destination: screenshot.jpeg
          width: 1280

      - name: Déclaration a11y
        continue-on-error: true
        timeout-minutes: 10
        uses: SocialGouv/dashlord-actions/declaration-a11y@bda592c644a12e09736c4884426abd37280faa2d # 1.44.0
        if: ${{ matrix.sites.tools['declaration-a11y'] }}
        with:
          url: ${{ matrix.sites.url }}
          output: scans/declaration-a11y.json

      - name: Wappalyzer scan
        if: ${{ matrix.sites.tools.wappalyzer }}
        uses: SocialGouv/wappalyzer-action@84f8eefc908ae35051802c73da6f8b1b936c2273 # branch : master
        continue-on-error: true
        timeout-minutes: 10
        with:
          url: "${{ matrix.sites.url }}"
          output: scans/wappalyzer.json

      - name: ZAP Scan
        if: ${{ matrix.sites.tools.zap }}
        uses: zaproxy/action-baseline@de8ad967d3548d44ef623df22cf95c3b0baf8b25 # v0.15.0
        continue-on-error: true
        timeout-minutes: 10
        with:
          token: "" # disable issue creation
          rules_file_name: "zap-rules.tsv"
          allow_issue_writing: false
          target: "${{ matrix.sites.url }}"
          cmd_options: "-a"

      - name: Lighthouse scan
        if: ${{ matrix.sites.tools.lighthouse }}
        continue-on-error: true
        timeout-minutes: 20
        uses: SocialGouv/dashlord-actions/lhci@bda592c644a12e09736c4884426abd37280faa2d # 1.44.0
        with:
          url: "${{ join(matrix.sites.subpages, ',') }}"

      - name: Mozilla HTTP Observatory
        if: ${{ matrix.sites.tools.http }}
        continue-on-error: true
        id: http
        timeout-minutes: 10
        uses: SocialGouv/httpobs-action@b1131f9d2670adf33189aa758c74545de8873378 # branch : master
        with:
          url: "${{ matrix.sites.url }}"
          output: "scans/http.json"

      - name: Mozilla HTTP Observatory retry
        if: steps.http.outcome=='failure'
        continue-on-error: true
        timeout-minutes: 10
        uses: SocialGouv/httpobs-action@b1131f9d2670adf33189aa758c74545de8873378 # branch : master
        with:
          url: "${{ matrix.sites.url }}"
          output: "scans/http.json"

      - name: Third-party scripts scan
        if: ${{ matrix.sites.tools.thirdparties }}
        continue-on-error: true
        timeout-minutes: 10
        uses: SocialGouv/thirdparties-action@master
        id: thirdparties
        with:
          url: "${{ matrix.sites.url }}"
          output: "scans/thirdparties.json"

      - name: Déclaration RGPD
        continue-on-error: true
        uses: SocialGouv/dashlord-actions/declaration-rgpd@bda592c644a12e09736c4884426abd37280faa2d # 1.44.0
        if: ${{ matrix.sites.tools['declaration-rgpd'] }}
        with:
          thirdparties: ${{ steps.thirdparties.outputs.json }}
          url: ${{ matrix.sites.url }}
          output: scans/declaration-rgpd.json

      # testssl.sh action needs an hostname to save its output so we build it here
      - name: Extract hostname
        id: hostname
        run: |
          HOSTNAME=$(echo "${{ matrix.sites.url }}" | sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/')
          echo "::set-output name=value::$HOSTNAME"

      - name: testssl.sh scan
        if: ${{ matrix.sites.tools.testssl }}
        continue-on-error: true
        timeout-minutes: 10
        uses: mbogh/test-ssl-action@6bad4e83e29bca36d5570a00736a0b9d63e52643 # NodeJS v20
        with:
          host: ${{ steps.hostname.outputs.value }}
          output: scans
          grade: "F"
          options: "--fast"

      - name: nmap vulnerabilities scan
        if: ${{ matrix.sites.tools.nmap }}
        continue-on-error: true
        timeout-minutes: 10
        uses: "MTES-MCT/nmap-action@35d94744caa271668174832306f9db5e61bd20c1" # branch : main
        with:
          host: ${{ steps.hostname.outputs.value }}
          outputDir: "scans"
          outputFile: "nmapvuln.json"
          withVulnerabilities: true
          raw: false

      - name: Nuclei scan
        if: ${{ matrix.sites.tools.nuclei }}
        continue-on-error: true
        timeout-minutes: 30
        uses: "SocialGouv/dashlord-nuclei-action@31e71ca2c2e7fde8cb4a872063f4b471a0e04c26" # branch : master
        with:
          url: ${{ matrix.sites.url }}
          output: "scans/nuclei.log"

      - name: Updown.io checks
        if: ${{ matrix.sites.tools.updownio }}
        continue-on-error: true
        timeout-minutes: 10
        uses: MTES-MCT/updownio-action@e364973d068215e4cffae8e4033a7a8712779c23 # v0.1.0
        with:
          apiKey: ${{ secrets.UPDOWNIO_API_KEY }}
          url: ${{ matrix.sites.url }}
          output: scans/updownio.json

      - name: Betagouv API scan
        if: ${{ matrix.sites.tools.betagouv }}
        continue-on-error: true
        timeout-minutes: 10
        id: betagouv
        uses: betagouv/dashlord-startup-action@93cbc26a096e16ca9b285e7e23b80f5535604ba6 # branch : main
        with:
          id: "${{ matrix.sites.betaId }}"
          output: "scans/betagouv.json"

      - name: Stats page from beta
        continue-on-error: true
        timeout-minutes: 10
        uses: "betagouv/check-url-action@4abfd436fe4cbe5f064f17cb969ce6194b0bc716" # branch : main
        if: ${{ matrix.sites.tools.stats }}
        id: stats
        with:
          url: ${{ steps.betagouv.outputs.stats_url }}
          output: scans/stats.json
          minExpectedRegex: ^stat
          exactExpectedRegex: ^stats$

      - name: Stats page retry on url
        continue-on-error: true
        timeout-minutes: 10
        uses: "betagouv/check-url-action@4abfd436fe4cbe5f064f17cb969ce6194b0bc716" # branch : main
        if: ${{ steps.stats.outcome=='failure' }}
        with:
          url: ${{ format('{0}/stats', matrix.sites.url) }}
          output: scans/stats.json
          minExpectedRegex: ^stat
          exactExpectedRegex: ^stats$

      - name: Budget page from beta
        continue-on-error: true
        timeout-minutes: 10
        uses: "betagouv/check-url-action@4abfd436fe4cbe5f064f17cb969ce6194b0bc716" # branch : main
        if: ${{ matrix.sites.tools.budget_page }}
        id: budget_page
        with:
          url: ${{ steps.betagouv.outputs.budget_url }}
          output: scans/budget_page.json
          exactExpectedRegex: ^budget$

      - name: Budget page retry on url
        continue-on-error: true
        timeout-minutes: 10
        uses: "betagouv/check-url-action@4abfd436fe4cbe5f064f17cb969ce6194b0bc716" # branch : main
        if: ${{ steps.budget_page.outcome=='failure' }}
        with:
          url: ${{ format('{0}/budget', matrix.sites.url) }}
          output: scans/budget_page.json
          exactExpectedRegex: ^budget$

      - name: Open Github repository
        continue-on-error: true
        timeout-minutes: 10
        uses: "betagouv/check-url-action@4abfd436fe4cbe5f064f17cb969ce6194b0bc716" # branch : main
        if: ${{ matrix.sites.tools.betagouv }}
        with:
          url: ${{ steps.betagouv.outputs.github_repository }}
          output: scans/github_repository.json

      - name: Dependabot vulnerabilities alerts
        continue-on-error: true
        timeout-minutes: 10
        if: ${{ matrix.sites.tools.dependabot && matrix.sites.repositories }}
        uses: "MTES-MCT/dependabotalerts-action@3d7d27756ad09279b6893a050aa79bcc5cdd3c48" # branch : main
        with:
          token: ${{ secrets.DEPENDABOTALERTS_TOKEN }}
          repositories: ${{ join(matrix.sites.repositories) }}
          output: scans/dependabotalerts.json
          maxAlerts: 100
          states: "OPEN"

      - name: Code quality alerts
        if: ${{ matrix.sites.tools.codescan && matrix.sites.repositories }}
        continue-on-error: true
        uses: "MTES-MCT/codescanalerts-action@e8fe792a23b2378c1428a24de787011333a37518" # branch : main
        with:
          token: ${{ secrets.CODESCANALERTS_TOKEN }}
          repositories: ${{ join(matrix.sites.repositories) }}
          output: scans/codescanalerts.json
          state: open

      - name: Trivy
        continue-on-error: true
        timeout-minutes: 10
        if: ${{ matrix.sites.tools.trivy && matrix.sites.docker }}
        uses: SocialGouv/dashlord-actions/trivy@bda592c644a12e09736c4884426abd37280faa2d # 1.44.0
        with:
          images: ${{ join(matrix.sites.docker) }}
          output: scans/trivy.json

      - name: sonarcloud scan
        if: ${{ matrix.sites.tools.sonarcloud }}
        id: sonarcloud
        continue-on-error: true
        timeout-minutes: 10
        uses: SocialGouv/dashlord-actions/sonarcloud@bda592c644a12e09736c4884426abd37280faa2d # 1.44.0
        with:
          repos: ${{ join(matrix.sites.repositories) }}
          output: "scans/sonarcloud.json"

      - name: Detect 404s
        continue-on-error: true
        timeout-minutes: 10
        uses: "SocialGouv/detect-404-action@d9cfb10876e3403195e7cc2a306d2b166d1792b8" # branch : master
        if: ${{ matrix.sites.tools['404'] }}
        with:
          url: ${{ matrix.sites.url }}
          output: scans/404.json

      - uses: SocialGouv/dashlord-actions/save@bda592c644a12e09736c4884426abd37280faa2d # 1.44.0
        with:
          url: ${{ matrix.sites.url }}
          # only clean up previous stats when all tools runned
          cleanup: ${{ github.event.inputs.tool == 'all' && true || false }}

      - uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
        with:
          add: "results"
          author_name: "incubateur-ademe-admin"
          author_email: "153178900+incubateur-ademe-admin@users.noreply.github.com"
          message: "update: ${{ matrix.sites.url }}"
          pull: "--rebase --autostash"
